
services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mysql/mysql-server:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app_test}
      # You should definitely change the password in production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
    healthcheck:
      test: mysqladmin ping -h localhost -p $$MYSQL_ROOT_PASSWORD
      timeout: 5s
      retries: 5
      start_period: 0s
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
